### PR TITLE
Fix issues with blockreassurance

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | JS wasn't working because of eslint, material icons added only one icon from what I saw so I removed it (it was a reason why BO wasn't displayed properly), fixed webpack path for assets, etc.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#22892.
| How to test?  | Follow PrestaShop/PrestaShop#22892 and test module as an overall

### CODE REVIEW

**Comment by matks** [comment]
> JS wasn't working because of eslint

@kpodemski Can you explain a little more? I remember we had an issue with eslint in the past, so I wonder if it's the same issue coming back or a 2nd scenario

**Comment by kpodemski** [comment]
@matks 

it's because `this` inside arrow function has different context

**Comment by NeOMakinG** [comment]
I notified that this module CSS was loaded before the core one, is this enough to fix https://github.com/PrestaShop/PrestaShop/issues/22892#issuecomment-854993387 ? Overwise, everything looks legit there :)

**Comment by kpodemski** [comment]
@NeOMakinG 

this issue was caused by material icons, and to be honest I didn't find any reason to include a custom material icon set here so I removed it, other issues were found because I couldn't use module without fixes related to `this` :D

**Comment by NeOMakinG** [comment]
@kpodemski ofc, as we already have material-icons on core side, well!

**Review by NeOMakinG — APPROVED** [review]
lgtm

**Review by Progi1984 — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-core-developers 

I don't have access, QA label and milestone needed

**Comment by sarahdib** [comment]
Hello @kpodemski 
With this PR the bug is fixed but a new one appear : 
https://drive.google.com/file/d/1-sA8KYfkylqHRv4Y-JkYETOCg1ukXBqa/view

Without this PR 
https://drive.google.com/file/d/1CcabYDMy9X5LYY3VBxKvVljKnGzzyE9a/view

**Comment by matks** [comment]
@kpodemski friendly reminder 😉

**Comment by kpodemski** [comment]
@matks I'll get back to this module in September 👍

**Comment by matks** [comment]
> @matks I'll get back to this module in September 👍

@kpodemski I think you got some other important stuff to do since September 😄 

Shall we close this PR? If we close it ; it does not mean it will never be done. It might be done by someone else.

**Pull request closed without merging**
