### PR TITLE
Use hmtl input color instead of simonwep/pickr

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | simonwep/pickr is not updated for over 18 months, while default HTML input  color is much simpler and lighter
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [Issue 27186](https://github.com/PrestaShop/PrestaShop/issues/27186) (partially). Related to [prestashop-ui-kit/issues/196](https://github.com/PrestaShop/prestashop-ui-kit/issues/196)
| How to test?  | 1. Apply this PR changes <br> 2. In terminal run: <br> &nbsp; `cd /modules/blockreassurance` <br> &nbsp;  `rm -rf node_modules` <br> &nbsp;  `npm install` <br> &nbsp; `npm run build`<br> 3. Clear Web browser cache and PrestaShop BO cache <br> 4. Check Color Picker feature in the module BO Config's Appearance to make sure Icon color and Text color can be picked and saved there, then showed in FO accordingly, as usual. <br>_(this PR fixed misalignment issue with color's label and input in xs and sm screens as well :)_

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
I agree that it's better to use native color pickers, but I'll ping @MatShir, so he can approve this and be aware of the change :)

**Comment by kpodemski** [comment]
ping @MatShir

**Review by MatShir — APPROVED** [review]
LGTM !

**Review by florine2623 — APPROVED** [review]
Hello @leemyongpakvn ,

LGTM ✅ 

https://user-images.githubusercontent.com/16019289/226947247-5d13788a-da90-4364-9584-35ec4bcd16b5.mov

Changes are well taken into account in BO and FO ^^
Thanks!

**Comment by jolelievre** [comment]
Sorry, @leemyongpakvn seems like there's a small conflict on pakcge.json, probably another dependency was updated, can you fix the conflict, please?

**Comment by leemyongpakvn** [comment]
@jolelievre Sure, the conflict is solved now.

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you @leemyongpakvn 

well done 👏🏻

**Pull request merged**
