### PR TITLE
Release 5.1.3

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | New version
| Type?         | new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Exploratory tests of the module

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by djoelleuch** [comment]
Hello @kpodemski  ,

Some checks were not successful , could you please check . 

Thank you  !

**Review by MhiriFaten — COMMENTED** [review]
hello @kpodemski ,

I have checked the release with **PS_8.0.4** and **PS_1.7.8.9** and I noticed the following issue when I want to edit the image : 

PS_8.0.4 :x: 

[Capture vidéo du 16-06-2023 11:37:59.webm](https://github.com/PrestaShop/blockreassurance/assets/111756615/35aaa8e8-9136-4ae2-ab30-5bf382064a2e)

PS_1.7.8.9 :x: 

[Capture vidéo du 16-06-2023 11:49:39.webm](https://github.com/PrestaShop/blockreassurance/assets/111756615/5095806d-0a28-4118-97b4-23634612e359)

Could you check it please ?

**Comment by leemyongpakvn** [comment]
I see no problem on PS 1.7.8.9 and PS 8.1.0 when testing current dev branch with these scripts:
```
cd PrestaShop/modules
rm -rf blockreassurance
git clone https://github.com/PrestaShop/blockreassurance.git
cd blockreassurance
nvm use 16
npm install
npm run build
```

**Comment by kpodemski** [comment]
@leemyongpakvn, maybe it's tested to the images uploaded to the store working in the subdirectory? but I remember that it was fixed some time ago

**Comment by leemyongpakvn** [comment]
@kpodemski **MhiriFaten**'s reported issue happens when **Editing** personal icon after upgrade. The [old issue](PrestaShop/PrestaShop/issues/28264) happens when **Viewing** personal icon after upgrade (without prior Edit).
The first one looks like a JS bug or PHP bug come from other PR during _QA's multi testings_, then I suggest using `rm -rf` to make sure we don't inherit any bug from previous tests ;)
The latter looks like come from _Module Upgrade process_, that removes the module's existing `img_perso` folder with all personal images there, then I suggest to reopen it.

**Review by boherm — APPROVED** [review]

**Comment by leemyongpakvn** [comment]
We need a random miracle to pass PHPstan 1.7.6 :pray:

**Review by nicosomb — APPROVED** [review]

**Review by aniszr — COMMENTED** [review]
Hello @kpodemski 

I tested your PR and I noticed the following issues

**Tested with PS 8.0.5 & 8.1.1**

**_1. Content Tab_**

- Create a new reassurance block (Content tab):heavy_check_mark: 
- Delete reassurance :heavy_check_mark: 
- Chnage Block position by drag and drop :heavy_check_mark: 
- The image of new block is not displayed in Customer Reassurance list :x:

**_2. Display Tab_**

- Display is ok in : Global settings, Product pages and Checkout pages :heavy_check_mark: 

**_3. Appearance Tab_**

- Changing Icon color or Text color :x:  
- Save button don't generate any action :x:

**_4. FO display_**

- The new reassurance block is displayed without image :x:

See attached screenrecord:

https://github.com/PrestaShop/blockreassurance/assets/92626242/245d2613-9e00-4c0e-970c-bc8dee6cd4d8

Thanks!

**Comment by leemyongpakvn** [comment]
@aniszr Did you **clear your web browser cache** before testing ?
I tested with these steps:
1. cd modules
2. rm -rf blockreassurance
3. git clone https://github.com/PrestaShop/blockreassurance.git
4. clear the web browser cache
5. check module functions in both BO and FO and see no problem.

**Review by boherm — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello @kpodemski ,

I rechecked your PR and I noticed that [the issue mentioned](https://github.com/PrestaShop/blockreassurance/pull/565#pullrequestreview-1483222507) still exists with **PS_8.0.5** :x: with a fresh install and cleared cache.

Checked with Chrome :x: 

[Untitled_ Sep 4, 2023 10_28 AM.webm](https://github.com/PrestaShop/blockreassurance/assets/111756615/db9fc038-361f-41f4-81c8-4bd515a61a0a)


Checked with **Firefox** :x: 

[Untitled_ Sep 4, 2023 10_38 AM.webm](https://github.com/PrestaShop/blockreassurance/assets/111756615/e41ff86a-8b4c-4e11-a1f5-11e4777ef7a4)

**PS_8.1.1** :x: 


[Untitled_ Sep 4, 2023 10_09 AM.webm](https://github.com/PrestaShop/blockreassurance/assets/111756615/0120d3af-8a69-4dac-b148-af84ecb9dd6b)


Could you recheck it please?

**Comment by leemyongpakvn** [comment]
@MhiriFaten I see you used `gh pr checkout 565` in _Checked with Chrome_ screencast, but don't know what you did prior. Please provide more information about how you made a fresh install before that command (eg: uninstall with files deleted options then install v5.1.2 in BO, or rm -rf then `git clone` in Terminal).

**Comment by kpodemski** [comment]
@leemyongpakvn I'm starting to think that it might be related to the shop being in the directory called x.y.z

**Comment by leemyongpakvn** [comment]
@kpodemski Maybe, we need a QA who can test this PR in a simpler directory.
Beside that, I doubt `gh pr checkout 565` is not the correct way to test this PR:
1. When I tried unsintall the module with :white_check_mark: Optional: delete module folder after uninstall, reinstall v5.1.2 in BO, then `cd modules/blockreassurance` & `gh pr checkout 565` in Terminal, it breaks the whole site.
2. All files changed of this PR were already merged to dev branch, so `git clone https://github.com/PrestaShop/blockreassurance.git` is the best way to make a fresh install.

@florine2623 I wonder if QA team has a standard procedure to test a Release PR like this one :question:

**Comment by kpodemski** [comment]
@leemyongpakvn there is a process to test such releases, and `gh pr checkout 565` should definitely not break your site, maybe you forgot to run `composer install --no-dev`?

We have to test it in the subdirectory. I tested it using multistore and virtual URI and it worked fine, but I didn't test it in the subdirectory.

**Comment by MhiriFaten** [comment]
@leemyongpakvn I meant that it can't be a cache issue as long as I clear the cache and the PR was added on a fresh installed shop.

**Comment by leemyongpakvn** [comment]
@MhiriFaten OK. Then you can try **Krystian**'s suggestion: using a simpler directory :)

**Review by boherm — APPROVED** [review]

**Comment by matks** [comment]
I just tried to install blockreassurance v5.1.3 inside a subfolder named `1.2.3` and it works very well for me, I cannot reproduce the issues encountered by QA team. I will suggest a pair testing.

**Review by florine2623 — APPROVED** [review]
Hello all,

On my end, I can reproduce any of the issues mentioned by @MhiriFaten and @aniszr 😅 

Here are the screenrecords:

About this comment 
 https://github.com/PrestaShop/blockreassurance/pull/565#pullrequestreview-1483222507

PS 8.0.5 ✅ 

https://github.com/PrestaShop/blockreassurance/assets/16019289/039663c0-fef6-4f37-9183-55715ad02efb

PS 1.7.8.10 ✅ 

https://github.com/PrestaShop/blockreassurance/assets/16019289/d25b1cfe-8264-4ba4-acdc-2225f72eb28d

About this comment 
https://github.com/PrestaShop/blockreassurance/pull/565#pullrequestreview-1600458194

PS 8.1.2 ✅ 

https://github.com/PrestaShop/blockreassurance/assets/16019289/02fde687-b514-4666-9b56-5d3d99864cdb

So it is QA ✅ 
Thanks all ^^

**Comment by matks** [comment]
Thank you @florine2623 !

I strongly suggest we do merge this PR only on Monday, I would feel safer 😊

**Comment by leemyongpakvn** [comment]
Thanks @florine2623, @kpodemski and @matks

**Pull request merged**
