### PR TITLE
Add Symfony 5 support

### PR DESCRIPTION
**Pull request by mvorisek**
Effectively only `composer.json` change, but also fixes EOL of text files and CS (required by CI - see https://github.com/PrestaShop/blockreassurance/pull/38/checks?check_run_id=408573323 ).

No BC breaks, it only adds support for Symfony 4.x and 5.x.

### CODE REVIEW

**Comment by mvorisek** [comment]
Effectively only `composer.json` change, but also fixes EOL of text files and CS ( required by CI - see https://github.com/PrestaShop/blockreassurance/pull/38/checks?check_run_id=408573323 ).

**Comment by mvorisek** [comment]
PR complete, CS fixed.

**Comment by mvorisek** [comment]
Can this PR be merged, any feedback?

**Comment by matks** [comment]
> Can this PR be merged, any feedback?

We're slower than you 😛

**Comment by SD1982** [comment]
No unwanted behavior on the blockreassurance module after applying this PR. Thanks for this one to @mvorisek

**Comment by PierreRambaud** [comment]
Thanks @mvorisek

**Pull request merged**
