### PR TITLE
Bump min compatibility to  PHP 7.1.3 and PS 1.7.7, module version to 6.0.0

### LINKED ISSUE #32841: Bump minimum compatibility to PHP 7.1.3 and PS 1.7.7 for Native Modules
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Many native modules are keeping support for PHP 5.6 or even PHP 5.4 like [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/v3.1.2/composer.json), [ps_languageselector](https://github.com/PrestaShop/ps_languageselector/blob/v2.1.3/composer.json), and many others :). It is a security issue because PHP 5.6 was EOL since 31 Dec 2018, and it also [prevents phpstan 0.12 running inside composer.json](https://github.com/PrestaShop/ps_languageselector/blob/v2.1.3/tests/phpstan.sh). 
Beside that, we need to drop [PHP test for PHP 5.6 and PS 1.7.6 and previous version](https://github.com/PrestaShop/ps_languageselector/blob/v2.1.3/.github/workflows/php.yml) also.
- [x] blockreassurance
- [x] blockwishlist
- [x] pagesnotfound
- [x] productcomments
- [x] ps_emailalerts
- [ ] ps_facetedsearch
- [x] ps_googleanalytics
- [ ] ps_imageslider
- [ ] ps_languageselector
- [x] ps_linklist
- [ ] ps_mainmenu
- [ ] ps_newproducts
- [ ] ps_searchbar
- [ ] ps_sharebuttons

Progi1984 already bumped min compat to PHP 7.2 and PS 8.0 for blockwishlist and ps_linklist. I will apply changes for a dozen of modules, other contributors are welcomed to do the rest ;)

### Expected behavior

Bump minimum compatibility to PHP 7.1.3 and PS 1.7.7 in composer.json.
Drop PHP test for PHP 5.4 and PS 1.7.6 and previous version.

### Steps to reproduce

Please check links in Description.

### PrestaShop version(s) where the bug happened

1.7.4, 1.7.5, 1.7.6

### PHP version(s) where the bug happened

PHP 5.6

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please check the related issue.
| Type?         | improvement
| BC breaks?    | Does it break backward compatibility? yes
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes PrestaShop/Prestashop#32841
| How to test?  | CI green. Module works as usual on PS 1.7.7 and newer versions.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@leemyongpakvn it's all good, but I think we will wait for the release of 5.1.3 to let people use improvements you've made earlier on previous PrestaShop versions as well, sounds good?

**Comment by leemyongpakvn** [comment]
@kpodemski OK. I'm not in rush.

**Comment by matks** [comment]
@leemyongpakvn finally it's time 😄

**Review by kpodemski — APPROVED** [review]

**Review by LouisAUTHIE — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by leemyongpakvn** [comment]
@matks Rebased

**Review by matks — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @leemyongpakvn ,

Tested your PR on PS 1.7.7.8 PHP 7.1.33.

The module is not updated to 6.0.0.
It stays at v5.1.4.
Screenshot 2023-11-14 at 16 04 01

Could you check ?

On future versions (8.0.5, 8.1.2, develop), it is OK.

https://github.com/PrestaShop/blockreassurance/assets/16019289/1bcd520b-5dc0-4ca6-a080-3a43ce9f5d07

**Review by florine2623 — APPROVED** [review]
EDIT

The upgrade went well on 1.7.7.8.

Tested the following :
CRUD block reassurance
Check all tabs of modules
Check FO OK ✅ 

QA ✅

**Comment by leemyongpakvn** [comment]
Thanks all ;)

**Pull request merged**
