### PR TITLE
Fix get mime type

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix get mime type
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#20254
| How to test?  | See below

## How to test ?

See "failure scenario" described at the bottom of this PR: https://github.com/PrestaShop/blockreassurance/pull/55#issuecomment-666510451
- failure scenario should only happen with blockreassurance v5.0.0 on PS 1.7.6 ; on PS 1.7.7 it should be fine
- please verify that, when using this PR, the issue is solved on PS 1.7.6 and on PS 1.7.7 the issue is still not there

### CODE REVIEW

**Comment by matks** [comment]
@Progi1984 We need to revert my change where I modify the compatibility scope else QA will not be able to test on `1.7.6.x`.

Also we need to provide QA a specific scenario to observe the issue so they can compare before/after the PR

**Comment by Progi1984** [comment]
@matks Revert the compability scope.

**Comment by reanim8ed** [comment]
I get this error: https://bit.ly/3eYG6QF

**Comment by matks** [comment]
**I have collected a reproductible scenario for QA to be able to observe and explore the bug :**

1. install blockreassurance v5.0.0 on PS 1.7.6.7

2. modify file themes/classic/templates/catalog/product.tpl and replace line 148
```
{hook h='displayReassurance'}
```
by
```
{widget name="blockreassurance"}
```

This will now use blockreassurance as a [Widget](https://devdocs.prestashop.com/1.7/modules/concepts/widgets/) and not like a Hook.

3. open BO configuration page for the module and edit one of the 3 reassurance items: you need to upload a custom icon

4. now open the FO product page
- on some environments the page will crash
- on other environments the module will silently fail: the reassurance items will not be displayed (the block will appear empty) however you will see in Apache PHP logs the error `PHP Fatal error:  Uncaught Error: Call to undefined method ImageManager::getMimeType() in /modules/blockreassurance/classes/ReassuranceActivity.php:190`

This should be fixed by this PR

**Comment by matks** [comment]
> @Progi1984 I get this error:
> 
> image
> The problem occurs because **PS_BASE_URI** = '/'

I am sorry I dont understand this. It does not seem related to this PR, is it ?

**Comment by reanim8ed** [comment]
> > @Progi1984 I get this error:
> > image
> > The problem occurs because **PS_BASE_URI** = '/'
> 
> I am sorry I dont understand this. It does not seem related to this PR, is it ?

I found that the issue was introduced here: https://github.com/PrestaShop/blockreassurance/commit/37d0fb1eafe8c227281e12e9a1422980b0d76816#diff-e6316994746d2ce5be44c53e7d2527c3R190

ImageManager::getMimeType doesnt receive correct file location because str_replace returns wrong result then PS_BASE_URI = '/'.

Probably it should be registered as new issue.

**Comment by sarahdib** [comment]
@matks 
I try to reproduce the initial error but it's working without the PR for me : 
Capture d’écran 2020-09-01 à 15 59 51

**Comment by matks** [comment]
> @matks
> I try to reproduce the initial error but it's working without the PR for me :
> Capture d’écran 2020-09-01 à 15 59 51
> Capture d’écran 2020-09-01 à 16 00 22

Is this a 1.7.6 shop ?

**Comment by Progi1984** [comment]
@matks 
> failure scenario should only happen with blockreassurance v5.0.0 on PS 1.7.6 ; on PS 1.7.7 it should be fine
Yes

**Comment by Progi1984** [comment]
Thanks @sarahdib

**Comment by andromaque** [comment]
Hi @Progi1984 and @PierreRambaud,

This bug has been fixed a few months ago, targeted for version 5.1.0... but the current version is still 5.0.0.
When could we expect the release of the new version of the module?

Thank you

**Comment by KamikStudio** [comment]
I have a problem with blockreassurance as well. I changed to {widget h = 'displayReassurance'}, saved the file, refreshed the cache and received a message like in the screenshot
blockreassurance_problem

**Comment by KamikStudio** [comment]
@Progi1984  and when the solution?

**Comment by Frostbourn** [comment]
We need a fix.

**Comment by matks** [comment]
Hello everyone, there is a huge overload of work on teams right now and many other important items requiring focus which is why v5.1.0 is not out yet. However you can use the code from `dev` branch to fix your module in production while waiting for the official release although it is not validated by QA (I trust you can do the necessary testing to verify the behavior 😉 )
- this PR https://github.com/PrestaShop/blockreassurance/pull/55 fixes https://github.com/PrestaShop/PrestaShop/issues/20254
- the PR https://github.com/PrestaShop/blockreassurance/pull/60 is likely to fix https://github.com/PrestaShop/PrestaShop/issues/21752
- the PR https://github.com/PrestaShop/blockreassurance/pull/209 is likely to fix https://github.com/PrestaShop/blockreassurance/pull/209

> @matks I have a problem with blockreassurance as well. I changed to {widget h = 'displayReassurance'}, saved the file, refreshed the cache and received a message (the one before)
> 
> ContextErrorException
> .......iposomal.png): failed to open stream: No such file or directory

Hello @KamikStudio look at my PR https://github.com/PrestaShop/blockreassurance/pull/60 it might help you. I unfortunately don't have the time to continue working on it and there was a feedback from QA I could not process. You can pick up my work and even submit it as your own if you want to push the topic forward.

**Pull request merged**
