### PR TITLE
Replace jQueryAJAX by FetchAPI

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | old jQuery AJAX need to be replaced by modern and native FetchAPI. More details in the related discussion.
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes PrestaShop/PrestaShop/discussions/34239
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | 1. Get a clean dev branch then apply PR changes. <br> 2. FO - clear Browser cache, BO - clear PS cache (required as this PR has JS changes). <br> 3. Check to make sure that all features of module work as usual in both FO and BO, especially in BO > Modules > Content tab: Drag and Drop, Enable/Disable, Delete a Block in Grid view.

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Looks good to me. @leemyongpakvn did you update the JavaScript libraries mentioned in the diff? Or is it an unwanted change?

**Comment by leemyongpakvn** [comment]
@matks My changes is only in `_dev/back/index.js` file. 2 JavaScript libraries changes in the diff **really** come from bot's [PR 612](https://github.com/PrestaShop/blockreassurance/pull/612), and [PR 625](https://github.com/PrestaShop/blockreassurance/pull/625). Neither bot nor github build-release run `npm run build` so I must did it myself :)

**Review by boherm — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @leemyongpakvn ,

I have found a bug. I tested on `8.1.x` and `develop` branch.

Steps to reproduce :
- edit an existing block with a png image
- create 1 new block with the same png image as the previous one
- go to FO ✅ 
- delete the block you created
- go to FO, see warning and the existing block's image has disappeared :x:

Screenshot 2024-01-25 at 16 38 31

Could you check ? ^^

**Comment by leemyongpakvn** [comment]
@florine2623 I can reproduce that bug without applying this PR changes. The reason is simple: when you add a second block with the same png, the previous uploaded png will be overwritten; then when you request deleting the second block, the current code [delete its png without checking](https://github.com/PrestaShop/blockreassurance/blob/v5.1.4/controllers/admin/AdminBlockListingController.php#L71-L76) whether it is being used by other block.
So I think you can create a new issue and let this PR passed :)

**Review by florine2623 — APPROVED** [review]
Hi @leemyongpakvn ,

I could reproduce the issue without your PR ^^
So there's no need to block it indeed !

I haven't found anything else. This PR is QA ✅ 
Thanks!

**Comment by florine2623** [comment]
Issue created here : https://github.com/PrestaShop/PrestaShop/issues/35178

**Pull request merged**
