### PR TITLE
Use arrow function for back/index.js

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Use arrow function for back/index.js. ESlint was not happy with current implementation.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | CI should be green, even ESLint (which is optional)

### CODE REVIEW

**Review by MeKeyCool — APPROVED** [review]
Still two functions to transform with fat arrows ;)

**Comment by kpodemski** [comment]
Make sure to not use $(this) inside if you want to use arrow function. It won't work right now.

**Comment by matks** [comment]
> Make sure to not use $(this) inside if you want to use arrow function. It won't work right now.

Indeed 👍 so I use named functions then

**Review by NeOMakinG — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

Hello QA team. I don't think this PR has to be tested as it's a simple and relatively safe change. I would like to have your confirmation tho :)

**Pull request merged**
