### PR TITLE
Remove addons suggestion of module configuration

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Remove the Addons suggestion inside module configuration.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#26500
| How to test?  | Check that the Addons suggestion block is now removed.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

Thanks for your PR. After testing it, I'm facing an issue.
Go to BO > Modules > Configure blockreassurance
Go to Display Tab > Switch positions : an error appears

Screenshot 2021-11-04 at 12 33 36

Could you check please ?
Thanks !

**Comment by Progi1984** [comment]
@PrestaEdit Could you check the feedback of @florine2623 ? Thanks

**Comment by PierreRambaud** [comment]
> @PrestaEdit Could you check the feedback of @florine2623 ? Thanks

I'll have a check, I don't think it's related to this PR :thinking:

**Comment by PierreRambaud** [comment]
@florine2623 It should be better right now I fix the module in this PR :)

**Comment by florine2623** [comment]
Hello @PierreRambaud ,

Thanks for the update, I retested the PR. It is all good now :)
QA Approved ✅

**Comment by Progi1984** [comment]
Thanks @PrestaEdit & @PierreRambaud & @florine2623

**Pull request merged**
