### PR TITLE
Replace oudated jqueryuiSortable by modern SortableJS (manual rebase of PR 461)

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | As described in the Fixed ticket 30210, we need to replace jqueryuiSortable by another modern, active and popular library. I choose [SortableJS](https://github.com/SortableJS/Sortable) for blockreassurance module like Drupal devs had done with their core. <br> We can apply for ps_imageslider module as well. <br> In the near future, we can move SortableJS to the Core js/vendor to use as a common library because js/jquery/plugins/[jquery.sortable.js](https://github.com/PrestaShop/PrestaShop/blob/develop/js/jquery/plugins/jquery.sortable.js) is outdated also.
| Type?         | refacto
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/30210. Related to [Issue 27186](https://github.com/PrestaShop/PrestaShop/issues/27186) (partially)
| How to test?  | 1. Apply this PR changes <br> 2. In terminal run: <br> &nbsp; `cd /modules/blockreassurance` <br> &nbsp;  `npm install` <s>sortablejs --save</s> <br> &nbsp; `npm run build`<br> 3. Clear Web browser cache and PrestaShop BO cache <br> 4. Check sortable feature in the module BO Config's Content to make sure the item can be dragged, dropped and saved there, then showed in FO accordingly, as usual.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @leemyongpakvn 

I have checked your PR. Here is my feedback : 

- **Issue 1 :** The position icon is changed with PS8.0.0 : NOK 

**PS8.0.0 With PR : NOK** :x: 

image

**PS8.0.0 Without PR : OK** :heavy_check_mark: 

image

**PS1.7.8.8 with PR : OK** :heavy_check_mark: 

image

**-Issue 2 :** Errors warnings are displayed for each block in FO when we select an image (.jpeg, .png) and not an icon 

-Enable debug mode: ON
-Choose any block and edit it
-For the image field, choose an image icon
-GO to FO
-See error

This issue is already present without PR too. It can be fixed on this PR or we create a dedicated issue for it? What do you think?

image

image

image

https://user-images.githubusercontent.com/92912932/209324375-e2066b90-89af-4f02-8f7a-94a482873505.mp4


**Issue 3 :** An exception is displayed on FO only with PS1788 when putting an image 

**PS1788 With PR : NOK** :x: 

image

https://user-images.githubusercontent.com/92912932/209325669-2265bec8-3c62-4647-be02-793c557ee3d9.mp4

**Without PR : OK** :heavy_check_mark:  

image


Could you please check it?

Thank You!

**Comment by leemyongpakvn** [comment]
@HanaRebaiQA @NeOMakinG Thanks for checking.
For issue 1: it is not a bug, but an intended tweak. I replaced `drag_indicator` by `drag_handle` to fix the missing `drag_indicator` issue in old version of `material-icons` in [this module](https://github.com/PrestaShop/blockreassurance/blob/dev/package.json#L39) and [PS 1.7.8.7](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.7/admin-dev/themes/default/package.json#L31) dependencies. `material-icons` was replaced by `material-design-icons-iconfont` since [PS 1.7.8.8](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.8/admin-dev/themes/default/package.json#L31)
So test result for PS 1.7.8.8 and PS 8.0.x without PR will be the same, test result for PS 1.7.8.7 without PR will face missing drag_indicator issue.
For issue 2: I think we need to isolate this unrelated issue to a dedicated issue and solve separately.

**Comment by leemyongpakvn** [comment]
Screenshot for drag_indicator missing issue of blockreassurance Config in PS 1.7.8.7 Back-Ofice
blockReassurance_missingIcon_inPS1 7 8 7

**Comment by leemyongpakvn** [comment]
FYI, the `drag_indicator` missing issue in PS 1.7.8.7 (or prior) was also recorded in /pull/280 's HowToTest screenshot

**Comment by leemyongpakvn** [comment]
@NeOMakinG Is adding `sortablejs` to `package.json` dependencies preferable than `npm install sortablejs --save` in terminal ?

**Comment by paulnoelcholot** [comment]
Hello @leemyongpakvn,

I have tested your PR and I have a problem. It is not possible to do the "npm install", it freezes.
Can another QA test this PR?

image

**Comment by leemyongpakvn** [comment]
@paulnoelcholot Which nodejs and npm version did you use to test? 
I have no problem with 3 environments: node 14 and npm 7, node 16 and npm 8, node 18 and nvm 8. `npm install` take **19s** in node 14, 4m in node 16, and even **8m** in node 18.
Remove `node_modules` folder and `package-lock.json` before running `npm install` can help to solve the issue.

**Review by HanaRebaiQA — APPROVED** [review]
Hello @leemyongpakvn 

I have checked this PR again. 

It's OK for me.

- Check on PS8.0.0 : OK :heavy_check_mark: 
- Check on PS1788 : OK :heavy_check_mark: 

image


Thank You!

**Comment by nicosomb** [comment]
Thank you @leemyongpakvn

**Pull request merged**
