### PR TITLE
Migrate ObjectModel to Doctrine

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Migrate ObjectModel-based classes/ReassuranceActivity to Doctrine src/* <br> Deprecate ReassuranceActivity and all of its functions.
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | PrestaShop/PrestaShop/discussions/34472
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | 1. Apply this PR changes. <br> 2. In FO: clear browser cache & In BO: Performance > clear cache. <br> 3. Check all module features in both FO and BO to make sure they work as usual, especially multilingual feature for block title/description/link.

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
nice PR !

LGTM except a little nitpick of mine: 

since this module's minimal compatibility is with PrestaShop 1.7.7, which has PHP 7.1 as a minimal version...  I think it's ok (and good) to specify return types on functions directly, what do you think ?

**Comment by leemyongpakvn** [comment]
@matthieu-rolland Thanks for reminding. I must dropped `declare(strict_types=1)` and direct return type due to failure of `php-lint 7.1` yesterday. After checking again today, I see it was executed with `php-lint 5.6` in fact.
`php-lint 7.1` is fixed now, strict_types and direct return type come back, 100 lines of pure declare code are removed :thumbsup:

**Review by matthieu-rolland — APPROVED** [review]
LGTM 👍

**Comment by leemyongpakvn** [comment]
I have just found something wrong with Create new block ;)

**Comment by leemyongpakvn** [comment]
It's ready to review again now.

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @leemyongpakvn ,

Tested on 8.0, 8.1 and develop.

On all version of PS I have a fatal error.
Screenshot 2023-11-23 at 16 07 18

Screenshot 2023-11-23 at 16 08 20

Could you check ?
Thanks!

**Comment by leemyongpakvn** [comment]
@florine2623 It is a well-known issue, old SF configs in `var/cache` does not contain new added service :) You can solve it by applying _How to test's_ Step 2: BO > Performance > Clear Cache via Web browser, or running `rm -rf /var/cache` via Terminal.

**Review by AureRita — APPROVED** [review]
Hi @leemyongpakvn 

Thank you for your PR, I tested it and it seems to works as you can see : 

[Untitled_ Dec 4, 2023 3_06 PM.webm](https://github.com/PrestaShop/blockreassurance/assets/100699445/2603c6cc-56d9-4e2e-91b0-00637119beeb)

Tested on 8.0.x / 8.1.x / develop

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Review by boherm — APPROVED** [review]

**Comment by leemyongpakvn** [comment]
Thanks @matthieu-rolland and @AureRita

**Pull request merged**
