### PR TITLE
Fix removing previous module files in PHPStan tests

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The previous way of removing the directory didn't work correctly.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Much less frustration thanks to it 😂 
| How to test?  | CI is 🟢

### CODE REVIEW

**Comment by matks** [comment]
Hi @kpodemski what does this mean

> DO NOT MERGE BEFORE RELEASE

When should we merge this?

**Comment by matks** [comment]
Thanks to @leemyongpakvn I understood that  "DO NOT MERGE BEFORE RELEASE" actually meant "we dont want to reset the merge PR once again 😭"

**Comment by kpodemski** [comment]
We can merge this. I'll get back to the `blockreassurance` release afterwards.

**Review by leemyongpakvn — APPROVED** [review]
Let's go

**Pull request merged**
